apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:latest
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: tukano_user
        - name: POSTGRES_PASSWORD
          value: secure_password
        - name: POSTGRES_DB
          value: tukano_db
        - name: PGDATA
          value: /var/lib/postgresql/data/db
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data/db
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: minikube-hostpath-pvc
---

apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  selector:
    app: postgres