apiVersion: apps/v1
kind: Deployment
metadata:
  name: tukano-app
  labels:
    app: tukano-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tukano-app
  template:
    metadata:
      labels:
        app: tukano-app
    spec:
      containers:
      - name: tukano-app
        image: diogodi/scc2425-webapp:latest
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://localhost:5432/tukano_db
        - name: SPRING_DATASOURCE_USERNAME
          value: tukano_user
        - name: SPRING_DATASOURCE_PASSWORD
          value: secure_password
        - name: SPRING_JPA_HIBERNATE_DDL_AUTO
          value: update
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "250m"

---

apiVersion: v1
kind: Service
metadata:
  name: tukano-app
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30080  
  selector:
    app: tukano-app

