apiVersion: apps/v1
kind: Deployment
metadata:
  name: tukano-app
  labels:
    app: tukano-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tukano-app
  template:
    metadata:
      labels:
        app: tukano-app
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: tukano-app
        image: jmll17/scc2425-webapp:latest
        ports:
        - containerPort: 8080 
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "250m"

---

apiVersion: v1
kind: Service
metadata:
  name: tukano-app
spec:
  type: NodePort
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30000  
  selector:
    app: tukano-app

